---
- name: "HandlerReloadConsul"
  ansible.builtin.systemd:
    name: consul-{{ consul_role }}.service
    state: reloaded
  become: true

- name: "HandlerRestartConsul"
  ansible.builtin.systemd:
    name: consul-{{ consul_role }}.service
    state: restarted
  become: true
...
