---
- name: "HandlerReloadConsul"
  ansible.builtin.systemd:
    state: reloaded
    name: consul-{{ consul_role }}.service
  become: true

- name: "HandlerRestartConsul"
  ansible.builtin.systemd:
    state: restarted
    name: consul-{{ consul_role }}.service
  become: true
...
